import AuthProvider from "./(component)/AuthProvider";
import Nav from "./(component)/Nav";
import "./globals.css";

export const metadata = {
  title: "Next Auth With Javascript",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-100">
          <Nav />
          <div className="m-2">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
